### ISSUE TITLE
Warning: Predicate arouter:new_route/5 not defined

### ISSUE THREAD

**Issue by arthwang** [rla/alternative-router#7]
Hi, 
I run into a little bit warning:
arouter.pl:272:	Warning:	Predicate arouter:new_route/5 not defined.

**Comment by rla** [comment]
Hello!

There is no such predicate in this version. What you get from here is documented in:
<https://github.com/rla/alternative-router/blob/master/README.md>

Someone forked this and overpublished the pack in the SWI packs list. I think that's what you got. I have no control over the pack list. I have tried to contact the developer who forked it but have received no reply.

Install using

```
pack_install('http://packs.rlaanemets.com/alternative-router/arouter-1.1.1.tgz').
```

if you want this version and skip the pack registry.

**Comment by arthwang** [comment]
Thank you very much!
No wonder that version doesn't be compatible with your simple-template package. You'd better publish your official version appreciatedly.
Thanks for your great works!
