### ISSUE TITLE
binding route goal on http_daemon

### ISSUE THREAD

**Issue by flashpixx** [rla/alternative-router#8]
Hello,

I try to use the route with ```http_daemon``` goal:

```prolog
:- use_module(library(http/http_unix_daemon)).
:- use_module(library(arouter)).

:- make_library_index( 'route', [ '*.prolog' ]).
:- initialization(http_daemon, main).
```

I try to add the ```handle_request``` to the program, but this does not work. So how can I bind the ```route``` goal to the server daemon?

**Comment by rla** [comment]
Hello!

I think you need something like this: <https://gist.github.com/rla/b448a07d567bcc69650566a23b23c668>.

See also docs for the `http_server_hook` predicate.

**Comment by flashpixx** [comment]
I try this also

```prolog
:- use_module(library(http/http_unix_daemon)).
:- use_module(library(arouter)).


http_unix_daemon:http_server_hook(Options) :-
    http_server(handle_request, Options).

handle_request(Request) :-
    (   aroute(Request)
    ->  true
    ;   http_dispatch(Request)).


:- route_get( hello/Name, handle_hello(Name) ).

handle_hello(Name):-
    format('Content-Type: text/plain; charset=UTF-8~n~n'),
    format('Hello ~w', [Name]).


:- initialization(http_daemon, main).
```

But the error is ```ERROR: service `true' does not exist```. IMHO the ```handle_request``` is not bind correctly. With the example within the readme ```http_server``` it works, but with ```http_daemon``` it does not , but for a service I need the daemon call

**Comment by rla** [comment]
Tested this:

```prolog
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_unix_daemon)).
:- use_module(library(arouter)).

:- route_get(hello/Name, handle_hello(Name)).

handle_hello(Name):-
    format('Content-Type: text/plain; charset=UTF-8~n~n'),
    format('Hello ~w', [Name]).

http_unix_daemon:http_server_hook(Options):-
    http_server(handle_request, Options).

handle_request(Request):-
    (   route(Request)
    ->  true
    ;   http_dispatch(Request)).

:- initialization(http_daemon, main).
```

With command: `swipl -s test.pl -- --port=8000 --interactive=true`.

**Comment by flashpixx** [comment]
Sorry, no it does not work, same error message, I run the script with ```swipl -O server.prolog --no-fork --port 8080``` I need the ```--no-fork``` option for the daemon, but I tested it with ```-s``` and ```--interactive=true```. My SWI-Prolog version is 7.6.4

**Comment by flashpixx** [comment]
I just reinstall the package with the URL, after that it works, thanks
